# Generated by Django 3.2.9 on 2022-02-08 12:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='Почта')),
                ('name', models.CharField(max_length=20, verbose_name='Имя')),
                ('surname', models.CharField(max_length=20, verbose_name='Фамилия')),
                ('password', models.CharField(max_length=128, verbose_name='Пароль')),
                ('gender', models.CharField(choices=[('m', 'male'), ('f', 'female')], help_text='Введите m(male) или f(female)', max_length=1, verbose_name='Пол')),
                ('avatar', models.ImageField(upload_to='avatars/%Y/%m/%d/', verbose_name='Аватарка')),
            ],
            options={
                'verbose_name': 'Участник',
                'verbose_name_plural': 'Участники',
            },
        ),
    ]
