# Generated by Django 3.2.9 on 2022-02-09 12:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dating', '0002_auto_20220208_1629'),
    ]

    operations = [
        migrations.CreateModel(
            name='Sympathy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client', to=settings.AUTH_USER_MODEL)),
                ('client_liked', models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, related_name='client_liked', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
